dist: bionic

language: generic

services:
  - mysql
  - postgresql

env:
  - ADA_PROJECT_PATH="${TRAVIS_BUILD_DIR}/install/share/gpr"

install:

  # Install GNAT FSF
  - sudo apt-get -y install gnat gprbuild liblzma-dev libcurl4-openssl-dev libxmlada-sax7-dev
  - sudo apt-get -y install libaws3.3.2.2-dev libxmlada-sax7-dev libxmlada-dom7-dev libgpr1-dev

  # Install databases for Ado
  - sudo apt-get -y install sqlite3 libsqlite3-dev
  - sudo apt-get -y install postgresql-client libpq-dev
  - sudo apt-get -y install libmariadb-dev
  - sudo apt-get -y install xsltproc autotools-dev

  # Install lcov for coverage
  - sudo apt-get -y install lcov

before_script:
  - psql -c 'CREATE DATABASE ado_test;' -U postgres
  - psql -c 'CREATE DATABASE awa_test;' -U postgres
  - psql -c "CREATE ROLE ado WITH PASSWORD 'ado'" -U postgres
  - psql -c "CREATE ROLE awa_user WITH PASSWORD 'awa_pass'" -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ado_test;'
  - mysql -e "CREATE USER 'ado_test' IDENTIFIED BY '';"
  - mysql -e "GRANT ALL PRIVILEGES ON 'ado_test.*' TO 'ado_test'@'%';"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS awa_test;'
  - mysql -e "CREATE USER 'awa_user' IDENTIFIED BY '';"
  - mysql -e "GRANT ALL PRIVILEGES ON 'awa_user.*' TO 'awa_test'@'%';"
  - mysql -e "FLISH PRIVILEGES;"

script:
  - ./configure --enable-coverage --prefix=${TRAVIS_BUILD_DIR}/install
  - make -s build install
  - make -s -i test

after_success:
  - make update-coverage
